Repository py3-coder/Hacktober_Repo_22, pull requests merged in 2022-10, with the labels that each got.

#21 Adding My Book Apps on Android Folder
  Android/MyBookApps/.gitignore
  Android/MyBookApps/.idea/.gitignore
  Android/MyBookApps/README.md
  Android/MyBookApps/app/.gitignore
  Android/MyBookApps/app/build.gradle
  Android/MyBookApps/app/proguard-rules.pro
  Android/MyBookApps/app/src/androidTest/java/com/hacktoberfest/mybookapps/ExampleInstrumentedTest.kt
  Android/MyBookApps/app/src/main/AndroidManifest.xml
  Android/MyBookApps/app/src/main/java/com/hacktoberfest/mybookapps/MainActivity.kt
  Android/MyBookApps/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  Android/MyBookApps/app/src/main/res/drawable/ic_launcher_background.xml
  Android/MyBookApps/app/src/main/res/layout/activity_main.xml
  Android/MyBookApps/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  Android/MyBookApps/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  Android/MyBookApps/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  Android/MyBookApps/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  Android/MyBookApps/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  Android/MyBookApps/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  Android/MyBookApps/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  Android/MyBookApps/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  Android/MyBookApps/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  Android/MyBookApps/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  Android/MyBookApps/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  Android/MyBookApps/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  Android/MyBookApps/app/src/main/res/values-night/themes.xml
  Android/MyBookApps/app/src/main/res/values/colors.xml
  Android/MyBookApps/app/src/main/res/values/strings.xml
  Android/MyBookApps/app/src/main/res/values/themes.xml
  Android/MyBookApps/app/src/main/res/xml/backup_rules.xml
  Android/MyBookApps/app/src/main/res/xml/data_extraction_rules.xml
  Android/MyBookApps/app/src/test/java/com/hacktoberfest/mybookapps/ExampleUnitTest.kt
  Android/MyBookApps/build.gradle
  Android/MyBookApps/gradle.properties
  Android/MyBookApps/gradle/wrapper/gradle-wrapper.jar
  Android/MyBookApps/gradle/wrapper/gradle-wrapper.properties
  Android/MyBookApps/gradlew
  Android/MyBookApps/gradlew.bat
  Android/MyBookApps/settings.gradle
Labels: hacktoberfest-accepted

#24 BinarySearch.py
  CONTRIBUTING.md
  Python/Ass22_binarySearch.py
Labels: hacktoberfest-accepted

#27 Added a Python Script
  CONTRIBUTING.md
  Python/iss.py
Labels: hacktoberfest-accepted

#31 Binary Search with example
  CONTRIBUTING.md
  Java/SearchInRotatedSortedArray.java
Labels: hacktoberfest-accepted

#32 Create Merge_Sort.java
  CONTRIBUTING.md
  Java/Merge_Sort.java
Labels: Need Fix.

#33 Revert "Create Merge_Sort.java"
  CONTRIBUTING.md
  Java/Merge_Sort.java
Labels: hacktoberfest-accepted

#35 added a program and added my info in contribution
  C/populatearray.c
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#36 Added Data Science Project
  CONTRIBUTING.md
  Data-Science/Posture_Detection_and_Correction_ML/.gitignore
  Data-Science/Posture_Detection_and_Correction_ML/Hack 5.0_ FixYourSelf.pdf
  Data-Science/Posture_Detection_and_Correction_ML/Procfile
  Data-Science/Posture_Detection_and_Correction_ML/README.md
  Data-Science/Posture_Detection_and_Correction_ML/Screenshots/1.png
  Data-Science/Posture_Detection_and_Correction_ML/Screenshots/10.png
  Data-Science/Posture_Detection_and_Correction_ML/Screenshots/11.png
  Data-Science/Posture_Detection_and_Correction_ML/Screenshots/12.png
  Data-Science/Posture_Detection_and_Correction_ML/Screenshots/13.png
  Data-Science/Posture_Detection_and_Correction_ML/Screenshots/2.png
  Data-Science/Posture_Detection_and_Correction_ML/Screenshots/3.png
  Data-Science/Posture_Detection_and_Correction_ML/Screenshots/4.png
  Data-Science/Posture_Detection_and_Correction_ML/Screenshots/5.png
  Data-Science/Posture_Detection_and_Correction_ML/Screenshots/6.png
  Data-Science/Posture_Detection_and_Correction_ML/Screenshots/7.png
  Data-Science/Posture_Detection_and_Correction_ML/Screenshots/8.png
  Data-Science/Posture_Detection_and_Correction_ML/Screenshots/9.png
  Data-Science/Posture_Detection_and_Correction_ML/app.py
  Data-Science/Posture_Detection_and_Correction_ML/requirements.txt
  Data-Science/Posture_Detection_and_Correction_ML/se_hackethon_project/__init__.py
  Data-Science/Posture_Detection_and_Correction_ML/se_hackethon_project/__init__.pyc
  Data-Science/Posture_Detection_and_Correction_ML/se_hackethon_project/forms.py
  Data-Science/Posture_Detection_and_Correction_ML/se_hackethon_project/models.py
  Data-Science/Posture_Detection_and_Correction_ML/se_hackethon_project/routes.py
  Data-Science/Posture_Detection_and_Correction_ML/se_hackethon_project/site.db
  Data-Science/Posture_Detection_and_Correction_ML/se_hackethon_project/static/assets/model/jeelizFaceTransferNNC.json
  Data-Science/Posture_Detection_and_Correction_ML/se_hackethon_project/static/home.css
  Data-Science/Posture_Detection_and_Correction_ML/se_hackethon_project/static/main.css
  Data-Science/Posture_Detection_and_Correction_ML/se_hackethon_project/static/person.jpg
  Data-Science/Posture_Detection_and_Correction_ML/se_hackethon_project/static/profile_pics/2333b06ef589a439.jpg
  Data-Science/Posture_Detection_and_Correction_ML/se_hackethon_project/static/profile_pics/6d60d88ecd779288.jpg
  Data-Science/Posture_Detection_and_Correction_ML/se_hackethon_project/static/profile_pics/737e45f688808fbd.jpg
  Data-Science/Posture_Detection_and_Correction_ML/se_hackethon_project/static/profile_pics/default.jpg
  Data-Science/Posture_Detection_and_Correction_ML/se_hackethon_project/static/profile_pics/default1.jpg
  Data-Science/Posture_Detection_and_Correction_ML/se_hackethon_project/static/profile_pics/e4dd3b0cc2e65fa4.jpg
  Data-Science/Posture_Detection_and_Correction_ML/se_hackethon_project/static/profile_pics/f31cd759bc769f09.jpg
  Data-Science/Posture_Detection_and_Correction_ML/se_hackethon_project/static/profile_pics/main_cam.ico
  Data-Science/Posture_Detection_and_Correction_ML/se_hackethon_project/static/src/css/style.css
  Data-Science/Posture_Detection_and_Correction_ML/se_hackethon_project/static/src/js/CantinaBand60.wav
  Data-Science/Posture_Detection_and_Correction_ML/se_hackethon_project/static/src/js/audio.js
  Data-Science/Posture_Detection_and_Correction_ML/se_hackethon_project/static/src/js/jeelizFaceTransfer.js
  Data-Science/Posture_Detection_and_Correction_ML/se_hackethon_project/static/src/js/main.js
  Data-Science/Posture_Detection_and_Correction_ML/se_hackethon_project/static/src/js/posture.js
  Data-Science/Posture_Detection_and_Correction_ML/se_hackethon_project/templates/account.html
  Data-Science/Posture_Detection_and_Correction_ML/se_hackethon_project/templates/allPosts.html
  Data-Science/Posture_Detection_and_Correction_ML/se_hackethon_project/templates/create_post.html
  Data-Science/Posture_Detection_and_Correction_ML/se_hackethon_project/templates/graph.html
  Data-Science/Posture_Detection_and_Correction_ML/se_hackethon_project/templates/home.html
  Data-Science/Posture_Detection_and_Correction_ML/se_hackethon_project/templates/index.html
  Data-Science/Posture_Detection_and_Correction_ML/se_hackethon_project/templates/layout.html
  Data-Science/Posture_Detection_and_Correction_ML/se_hackethon_project/templates/login.html
  Data-Science/Posture_Detection_and_Correction_ML/se_hackethon_project/templates/post.html
  Data-Science/Posture_Detection_and_Correction_ML/se_hackethon_project/templates/register.html
  Data-Science/Posture_Detection_and_Correction_ML/se_hackethon_project/templates/reset_request.html
  Data-Science/Posture_Detection_and_Correction_ML/se_hackethon_project/templates/reset_token.html
  Data-Science/Posture_Detection_and_Correction_ML/se_hackethon_project/templates/suggestion.html
  Data-Science/Posture_Detection_and_Correction_ML/se_hackethon_project/templates/user_posts.html
Labels: hacktoberfest-accepted

#39 Add insertion sort
  CONTRIBUTING.md
  Java/InsertionSort.java
Labels: hacktoberfest-accepted

#40 Added a JS folder and added Clock App
  CONTRIBUTING.md
  JS/Clock App/index.css
  JS/Clock App/index.html
Labels: hacktoberfest-accepted

#47 Add Armstrong number
  CONTRIBUTING.md
  Java/Armstrong_Numbers.java
Labels: hacktoberfest-accepted

#42 Create append_k_nodes.cpp
  CPP/append_k_nodes.cpp
Labels: hacktoberfest-accepted

#44 Created doubly_linked_list.cpp
  CPP/doubly_linked_list.cpp
Labels: hacktoberfest-accepted

#45 Created find_sqrt_using_bs.cpp
  CPP/find_sqrt_using_bs.cpp
Labels: hacktoberfest-accepted

#46 Created convert_decimal_to_binary.cpp
  CPP/convert_decimal_to_binary.cpp
Labels: hacktoberfest-accepted

#51 PR For Hactoberfest 2022
  CONTRIBUTING.md
  Python/FizzBuzz.py
Labels: hacktoberfest-accepted

#53 created hello world program in go
  Golang/helloworld.go
Labels: hacktoberfest-accepted

#54 created hello world in kotlin
  Kotlin/helloworld.kt
Labels: hacktoberfest-accepted

#55 Bracket_Balancer.cpp
  CONTRIBUTING.md
  CPP/Bracket_Balancer.cpp
Labels: hacktoberfest-accepted

#56 Added Student DB in CPP
  CONTRIBUTING.md
  CPP/student database.cpp
Labels: hacktoberfest-accepted

#57 added space prediction under Data Science
  CONTRIBUTING.md
  Data-Science/Spaceship_titanic_ML/.ipynb_checkpoints/Space_Titanic_Predictions-checkpoint.ipynb
  Data-Science/Spaceship_titanic_ML/Answers.csv
  Data-Science/Spaceship_titanic_ML/Space_Titanic_Predictions.ipynb
  Data-Science/Spaceship_titanic_ML/sample_submission.csv
  Data-Science/Spaceship_titanic_ML/spaceship-titanic.zip
  Data-Science/Spaceship_titanic_ML/test.csv
  Data-Science/Spaceship_titanic_ML/train.csv
Labels: hacktoberfest-accepted

#63 BinarySearch
  Java/BinarySearchWithExample
Labels: hacktoberfest-accepted

#65 Created an Image Resizer to Square project (JS)
  CONTRIBUTING.md
  JS/Image-resize-Square/README.md
  JS/Image-resize-Square/app.js
  JS/Image-resize-Square/bg.jpg
  JS/Image-resize-Square/example-1.png
  JS/Image-resize-Square/example-2.png
  JS/Image-resize-Square/image.jpg
  JS/Image-resize-Square/index.html
  JS/Image-resize-Square/style.css
Labels: hacktoberfest-accepted

#68 created a file linear_search.cpp
  CPP/linear_search.cpp
Labels: hacktoberfest-accepted

#69 created a file shift_zero.cpp
  CPP/shift_zero.cpp
Labels: hacktoberfest-accepted

#70 created a file remove_duplicate.cpp
  CPP/remove_duplicate.cpp
Labels: hacktoberfest-accepted

#71 created a file insert.cpp
  CPP/insert.cpp
Labels: hacktoberfest-accepted

#72 created a file sec_largest.cpp
  CPP/sec_largest.cpp
Labels: hacktoberfest-accepted

#81 Add:C++ code of Reverse_Vowels
  CONTRIBUTING.md
  CPP/reversevowels.cpp
Labels: hacktoberfest-accepted

#83 Added N digits of Pi in Python
  CONTRIBUTING.md
  Python/Pi upto nth digit/Calculation_formula.jpg
  Python/Pi upto nth digit/n_digits_of_pi.py
Labels: hacktoberfest-accepted

#50 House price prediction
  CONTRIBUTING.md
  Data-Science/house price/dataset/Bengaluru_House_Data.csv
  Data-Science/house price/model/Untitled.ipynb
Labels: hacktoberfest-accepted

#67 added sliding window technique
  Java/slidingwindow.java
Labels: hacktoberfest-accepted

#88 first commit
  CONTRIBUTING.md
  Python/String.py
Labels: hacktoberfest-accepted

#89 Created a file BoxConstructor.java
  CONTRIBUTING.md
  Java/BoxConstructor.java
Labels: hacktoberfest-accepted

#93 Added Bubble Sort in Golang and updated contributing.md
  CONTRIBUTING.md
  Golang/bubblesort.go
Labels: hacktoberfest-accepted

#97 Created hello.sh
  Shell/hello.sh
Labels: hacktoberfest-accepted

#96 created hcf.go
  Golang/hcf.go
Labels: hacktoberfest-accepted

#98 Added Selection Sort in Golang and typo fix in contributing.md
  CONTRIBUTING.md
  Golang/selectionsort.go
Labels: hacktoberfest-accepted

#66 Create Kandane_algorithm.cpp
  CPP/Kandane_algorithm.cpp
Labels: hacktoberfest-accepted

#99 Add Recurssion and linkedlist problems solution in python
  Python/linked list/linkedlist.py
  Python/recurssion/r1.py
Labels: hacktoberfest-accepted

#101 added linear search to python
  CONTRIBUTING.md
  Python/linear_seach.py
Labels: hacktoberfest-accepted

#103 Added NodeJS cli calculator app
  CONTRIBUTING.md
  NodeJS/cli-calculator/README.md
  NodeJS/cli-calculator/app.js
Labels: hacktoberfest-accepted

#105 Implemented Counting Sort in Golang
  Golang/countingsort.go
Labels: hacktoberfest-accepted

#106 added a new folder in JS and modified contributing.md
  CONTRIBUTING.md
  JS/rock_paper_scissor/main.html
  JS/rock_paper_scissor/script.js
  JS/rock_paper_scissor/style.css
Labels: hacktoberfest-accepted

#92 Email validation
  Python/email_validation_using_regex.py
Labels: hacktoberfest-accepted

#111 Added Code Template for Merge Sort
  CONTRIBUTING.md
  CPP/merge_sort.cpp
Labels: hacktoberfest-accepted

#113 added python ip tracker
  CONTRIBUTING.md
  Python/ip_tracker.py
Labels: hacktoberfest-accepted

#115 created file circularQueue.cpp and modified CONTRIBUTING.md file with the necessary details.
  CONTRIBUTING.md
  CPP/circularQueue.cpp
Labels: hacktoberfest-accepted

#48 Create Turtle.py
  CONTRIBUTING.md
  Python/Turtle.py
Labels: hacktoberfest-accepted

#108 created dice_combination.cpp
  CPP/dice_combination.cpp
Labels: hacktoberfest-accepted

#79 Simple FizzBuzz in Go
  CONTRIBUTING.md
  Golang/fizzbuzz.go
Labels: hacktoberfest-accepted

#87 Added C++ file Verical-order-traversal
  CONTRIBUTING.md
  CPP/vertical-order-traversal.cpp
Labels: hacktoberfest-accepted

#94 Implemented Bubble Sort
  CONTRIBUTING.md
  CPP/BubbleSort.cpp
  CPP/BubbleSort.exe
Labels: hacktoberfest-accepted

#95 Added info in contributing.md
  CONTRIBUTING.md
  Java/towerofhanoi.java
Labels: hacktoberfest-accepted

#102 diagonal traversal of binary tree
  CONTRIBUTING.md
  CPP/diagonalTraversalOfBinaryTree.cpp
Labels: hacktoberfest-accepted

#110 Contribution
  CONTRIBUTING.md
  Python/Digital_Clock.py
Labels: hacktoberfest-accepted

#116 Valorant success predictor
  CONTRIBUTING.md
  Python/BinarySearchTree.py
  Python/valorant.py
Labels: hacktoberfest-accepted

#123 created fibbonacci.cpp
  CPP/fibbonaci.cpp
Labels: hacktoberfest-accepted

#124 Created complex_number.cpp
  CPP/complex_number.cpp
Labels: hacktoberfest-accepted

#122 Student Management System
  Java/Student.java
Labels: hacktoberfest-accepted

#125 Created binary_search.cpp
  CPP/binary_search.cpp
Labels: hacktoberfest-accepted

#129 Created dnf_sort.cpp
  CPP/dnf_sort.cpp
Labels: hacktoberfest-accepted

#126 Laptop price prediction Web app
  CONTRIBUTING.md
  Data-Science/Laptop Price Prediction WebApp/Laptop App Model.ipynb
  Data-Science/Laptop Price Prediction WebApp/Laptop App Model.py
  Data-Science/Laptop Price Prediction WebApp/LaptopPriceApp.py
  Data-Science/Laptop Price Prediction WebApp/Procfile
  Data-Science/Laptop Price Prediction WebApp/Readme.md
  Data-Science/Laptop Price Prediction WebApp/model.pkl
  Data-Science/Laptop Price Prediction WebApp/requirements.txt
  Data-Science/Laptop Price Prediction WebApp/sample.txt
  Data-Science/Laptop Price Prediction WebApp/setup.sh
Labels: hacktoberfest-accepted

#131 created Binary_search_tree.cpp
  CPP/binary_search_tree.cpp
Labels: hacktoberfest-accepted

#143 Hacktoberfest-2022 Pull Request - Added dynamic_array.cpp
  CONTRIBUTING.md
  CPP/dynamic_array.cpp
Labels: hacktoberfest-accepted

#136 Added Python File
  CONTRIBUTING.md
  Python/minion.py
Labels: hacktoberfest-accepted

#141 updated c++
  CONTRIBUTING.md
  CPP/merge array.cpp
Labels: hacktoberfest-accepted

#140 Added Cpp code for minimizing coins
  CPP/minimizing_coins.cpp
Labels: hacktoberfest-accepted

#132 Added a very nice python trick to count digits
  CONTRIBUTING.md
  Python/Count_digits.py
Labels: hacktoberfest-accepted

#117 Added the Quick Sort Program in C++
  CONTRIBUTING.md
  CPP/Quick_Sort.cpp
Labels: hacktoberfest-accepted

#49 Creating TOH.java
  CONTRIBUTING.md
  Java/TOH.java
Labels: hacktoberfest-accepted

#150 added HTML
  CONTRIBUTING.md
  HTML/Description list.html
  HTML/I-frames.html
  HTML/List.html
  HTML/Meta and mediaqueries.html
  HTML/Tables.html
Labels: hacktoberfest-accepted

#162 Added a C++ file, containing Leetcode problem.
  CONTRIBUTING.md
  CPP/minimum_time_to_make_rope_colorful.cpp
Labels: hacktoberfest-accepted

#160 Updated the CONTRIBUTING.md file and Added Sudoku_backtracking.cpp
  CONTRIBUTING.md
  CPP/Sudoku_Backtracking.cpp
Labels: hacktoberfest-accepted

#153 Added setbit code
  C/set_bits.c
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#164 Weight of Minimum Spanning Tree Cpp Code
  CPP/minimum_spanning_tree.cpp
Labels: hacktoberfest-accepted

#169 Path Sum problem from Leetcode added.
  CPP/path_sum.cpp
Labels: hacktoberfest-accepted

#168 Create inttostring.py
  Python/inttostring.py
Labels: hacktoberfest-accepted

#167 Create doublylinkedlist.py
  Python/doublylinkedlist.py
Labels: hacktoberfest-accepted

#171 Create QrCodeGenerator.py
  Python/QrCodeGenerator.py
Labels: hacktoberfest-accepted

#155 Created butterfly_pattern.java
  Java/butterfly_pattern.java
Labels: hacktoberfest-accepted

#172 Create YouTubeDownloader.py
  YouTubeDownloader.py
Labels: hacktoberfest-accepted

#158 created check_pallindrome.java
  Java/check_pallindrome.java
Labels: hacktoberfest-accepted

#170 Create calculator-function.py
  CONNTRIBUTING.md
  Python/calculator-function.py
Labels: hacktoberfest-accepted

#166 Create remove.py
  Python/remove.py
Labels: hacktoberfest-accepted

#149 C++ Program
  CPP/ASCIIvalue.cpp
  CPP/Macros.cpp
Labels: hacktoberfest-accepted

#73 Create Armstrongnumber.py
  Python/Armstrongnumber.py
Labels: hacktoberfest-accepted

#26 Print Number Entered by User.cpp
  CPP/https:/hacktoberfest.com/participation/Print Number Entered by User.cpp
Labels: hacktoberfest-accepted

#59 Create Dijkstras.cpp
  CPP/Dijkstras.cpp
Labels: hacktoberfest-accepted, Need Fix.

#76 Create ImplementQueueUsingLinkedList.cpp
  CPP/ImplementQueueUsingLinkedList.cpp
Labels: hacktoberfest-accepted

#77 Create HeapSort .cpp
  CPP/HeapSort .cpp
Labels: hacktoberfest-accepted

#78 Create TopologicalSort.cpp
  CPP/TopologicalSort.cpp
Labels: hacktoberfest-accepted

#58 Added Leap year program in Python
  Python/LeapYear.py
Labels: hacktoberfest-accepted

#85 Create Longest-Palindromic-Substring.py
  Python/Longest-Palindromic-Substring.py
Labels: hacktoberfest-accepted

#90 Create Recursive Insertion Sort
  CPP/Recursive Insertion Sort
Labels: hacktoberfest-accepted

#91 Create liner_regression.py
  Python/liner_regression.py
Labels: hacktoberfest-accepted, Need Fix.

#100 Create CheckPowerOf2.py
  Python/CheckPowerOf2.py
Labels: hacktoberfest-accepted

#118 Added Problems and solution in Java
  Java/ChechkOddOrEven.java
  Java/Divide2numbers.java
  Java/Factorial.java
  Java/GcdOfNumber.java
  Java/PalindromeNumber.java
  Java/PowerOfA.java
  Java/PowerOfFour.java
  Java/PrimeNumbers.java
  Java/TrailingZeroInFactorial.java
Labels: hacktoberfest-accepted

#120 Created Array_rev.cpp program in CPP folder
  CPP/Array_rev.cpp
Labels: hacktoberfest-accepted

#137 Added GCD code with best complexity
  CPP/GCD.cpp
Labels: hacktoberfest-accepted

#165 WA automation
  Python/whatsapp_web_autorespond.py
Labels: hacktoberfest-accepted

#156 created half_pyramid.java
  Java/half_rectangle.java
Labels: hacktoberfest-accepted

#157 created hollow_rectangle.java
  Java/hollow_rectangle.java
Labels: hacktoberfest-accepted

#184 Number Dissector using Python
  Python/Number_Disector.py
Labels: hacktoberfest-accepted

#185 Create Decode Ways.java
  Java/Decode Ways.java
  Python/Infix_to_postfix.py
Labels: hacktoberfest-accepted

#173 Added add two nums
  Shell/addtwonum.sh
Labels: hacktoberfest-accepted

#174 Added by binayuchai
  CONNTRIBUTING.md
  CPP/spiral_matrix.cpp
Labels: hacktoberfest-accepted

#175 I add "POPUT using Javascript" and "Rock Paper scissor game using C++" and Python...
  CPP/Rock, Paper and Scissors Game.cpp
  HTML/POP up/404-tick.png
  HTML/POP up/index.html
  HTML/POP up/style.css
  Python/Calculator without operators.py
  Python/Password_Strength_Checker.py
  Python/snakegame.py
Labels: hacktoberfest-accepted

#176 added_max_element_in_each_row_program
  C/max_element_in_each_row.c
Labels: hacktoberfest-accepted

#177 Dijkstra’s Algorithm Shortest distance Java
  Java/DijkstrasAlgorithm.java
Labels: hacktoberfest-accepted

#178 Created a CSV file management using CPP /C++
  CPP/CSV_FileManagement.cpp
Labels: hacktoberfest-accepted

#180 BinarySearchTree
  Python/BinarySearchTre.py
Labels: hacktoberfest-accepted

#186 quize game
  Python/quiz.py
Labels: hacktoberfest-accepted

#187 Create Binary_Search.cpp in CPP Folder
  CPP/Binary_Search.cpp
Labels: hacktoberfest-accepted

#188 Create Quiz_Game.py
  Python/Quiz_Game.py
Labels: hacktoberfest-accepted

#190 Add Banking System
  Python/banking_system.py
Labels: hacktoberfest-accepted

#191 Balanced_Paranthesis
  CPP/Balanced Paranthesis.cpp
Labels: hacktoberfest-accepted

#192 Added sort-an-array-of-0s-1s-2s
  CPP/sort-an-array-of-0s-1s-2s.cpp
Labels: hacktoberfest-accepted

#193 Added Kadanes Algorithm
  Java/Kadanes.java
Labels: hacktoberfest-accepted

#194 Added Dijkstra algorithm
  Java/Dijkstra.java
Labels: hacktoberfest-accepted

#195 Added Book Allocation problem
  Java/Book_Allocation.java
Labels: hacktoberfest-accepted

#196 Added Krishnamurthy Number problem
  Java/Krishnamurthy.java
Labels: hacktoberfest-accepted

#197 HACKTOBERFEST-2022
  CPP/bubblesort.cpp
Labels: hacktoberfest-accepted

#207 Create Reversewords.java
  Reversewords.java
Labels: hacktoberfest-accepted

#201 Create 66. Plus One.py
  Python/66. Plus One.py
Labels: hacktoberfest-accepted

#199 added "hcf_gcd.py"
  Python/hcf_gcd.py
Labels: hacktoberfest-accepted

#203 Create checkPallindrome.cpp
  CPP/checkPallindrome.cpp
Labels: hacktoberfest-accepted

#204 Create nMeetingsInOneRoom.cpp
  CPP/nMeetingsInOneRoom.cpp
Labels: hacktoberfest-accepted

#205 Printing Initials of String
  C/Print Initials of String
Labels: hacktoberfest-accepted

#206 Selection_sort.cpp
  CPP/SelectionSort.cpp
Labels: hacktoberfest-accepted

#208 Add files via upload
  Python/Coffee Machine/main.py
Labels: hacktoberfest-accepted

#211 Encapsulation added
  Java/EncapsulationInJava/Encapsulation.jpg
  Java/EncapsulationInJava/main.java
Labels: hacktoberfest-accepted

#209 Created Hangman project in python and CountofWord in java
  Java/CountOfWords.java
  Python/Hangman/hangman.py
  Python/Hangman/hangman_art.py
  Python/Hangman/hangman_words.py
Labels: hacktoberfest-accepted

#210 Created Blackjack game project in Python and UniqueCharacter program in Java
  Java/UniqueCharacters.java
  Python/Blackjack/art.py
  Python/Blackjack/blackjack.py
Labels: hacktoberfest-accepted

#213 Number Of dice rolls with target sum problem added.
  CPP/NumberOfDiceRollsWithTargetSum.cpp
  CPP/Two_Sum.cpp
  CPP/binary_search.cpp
  CPP/bubblesort.cpp
Labels: hacktoberfest-accepted

#214 Add Tic Tac Toe game
  Python/tic_tac_toe.py
Labels: hacktoberfest-accepted

#218 python algorithm for finding anagram
  Python/an4gram.py
Labels: hacktoberfest-accepted

#220 Create tic_tac_toe.py
  Python/tic_tac_toe.py
Labels: hacktoberfest-accepted

#221 Create pythongame-rps.py
  Python/pythongame-rps.py
Labels: hacktoberfest-accepted

#222 python algo to find min and max in array
  Python/minm4x.py
Labels: hacktoberfest-accepted

#223 Createed sumOfArray.java
  Java/sumOfArray.java
Labels: hacktoberfest-accepted

#232 Create Rotate_LinkList.cpp
  CPP/Rotate_LinkList.cpp
Labels: hacktoberfest-accepted

#225 Add one row to tree problem added.
  CPP/add_one_row_to_tree.cpp
Labels: hacktoberfest-accepted

#227 data science project
  Data-Science/rj_voice/main.ipynb
  Data-Science/rj_voice/voice-classification.csv
Labels: hacktoberfest-accepted

#228 rotating donut imagery
  C/rotating_donut.c
Labels: hacktoberfest-accepted

#229 Hackerrank - Hacktoberfest
  CPP/Arrays -  Left Rotation.cpp
  CPP/Arrays - 2D Array - DS.cpp
  CPP/Arrays - Array Manipulation.cpp
  CPP/Arrays - Minimum Swaps 2.cpp
Labels: hacktoberfest-accepted

#231 Added Longest Palindromic Substring program in java
  Java/Longest Palindromic Substring.java
Labels: hacktoberfest-accepted

#235 Delete at the end in a Circular Linked list
  CPP/DeleteAtEnd.cpp
Labels: hacktoberfest-accepted

#236 Delete from any position in a circular linkedList
  CPP/DeleteAtAnyPos.cpp
Labels: hacktoberfest-accepted

#237 Revise prompt text, alert , suggestion message, check password length
  Python/Password_Strength_Checker.py
Labels: hacktoberfest-accepted
